## This file accompanies the manuscript: 
## Bartoszek, Pulka "Approximately simulating quadratic stochastic operators"

## This software comes AS IS in the hope that it will be useful WITHOUT ANY WARRANTY, 
## NOT even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
## Please understand that there may still be bugs and errors. Use it at your own risk. 
## We take no responsibility for any errors or omissions in this code or for any misfortune 
## that may befall you or others as a result of its use. Please send comments and report 
## bugs to Krzysztof Bartoszek at krzbar@protonmail.ch .

l_setup_norm0_1norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_1norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_1norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_1norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_1norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_1norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_norm0_10norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_10norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_10norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_10norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_10norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_10norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_10,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_10norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_norm1_1norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_1norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_1norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_1norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_1norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_1norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_1,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_1norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_norm1_10norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_10norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_10norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_10norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_10norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_10norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_10,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_10norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_norm0_01norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_01norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_01norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_01norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_01norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm0_01norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_01,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_01norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_norm1_01norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_01norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_01norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_01norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_01norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_norm1_01norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_1_01,vF=1,m=1,otherparams=list(outfile="norm0_1norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm1_01norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_exp1_norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp1_norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp1_norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp1_norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp1_norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp1_norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_1,vF=1,m=1,otherparams=list(outfile="exp1_norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp1_norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_exp10_norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp10_norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp10_norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp10_norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp10_norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp10_norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_10,vF=1,m=0.1,otherparams=list(outfile="exp10_norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp10_norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)

l_setup_exp01_norm05_n4_notsimulated<-list(n=4,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n4.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n4",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp01_norm05_n6_notsimulated<-list(n=6,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n6.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n6",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp01_norm05_n8_notsimulated<-list(n=8,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n8.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n8",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp01_norm05_n12_notsimulated<-list(n=12,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n12.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n12",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp01_norm05_n16_notsimulated<-list(n=16,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n16.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n16",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)
l_setup_exp01_norm05_n20_notsimulated<-list(n=20,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_exp_01,vF=1,m=10,otherparams=list(outfile="exp01_norm05_n20.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="exp01_norm05_n20",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topright",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=TRUE,b_approxBT=TRUE,b_approxBF=TRUE,b_popAlg=TRUE)


l_all_study_setups<-list(
c(index=1,l_setup_norm0_1norm05_n4_notsimulated),
c(index=2,l_setup_norm0_1norm05_n6_notsimulated),
c(index=3,l_setup_norm0_1norm05_n8_notsimulated),
c(index=28,l_setup_norm0_1norm05_n12_notsimulated),
c(index=37,l_setup_norm0_1norm05_n16_notsimulated),
c(index=46,l_setup_norm0_1norm05_n20_notsimulated),
c(index=4,l_setup_norm0_10norm05_n4_notsimulated),
c(index=5,l_setup_norm0_10norm05_n6_notsimulated),
c(index=6,l_setup_norm0_10norm05_n8_notsimulated),
c(index=29,l_setup_norm0_10norm05_n12_notsimulated),
c(index=38,l_setup_norm0_10norm05_n16_notsimulated),
c(index=47,l_setup_norm0_10norm05_n20_notsimulated),
c(index=7,l_setup_norm1_1norm05_n4_notsimulated),
c(index=8,l_setup_norm1_1norm05_n6_notsimulated),
c(index=9,l_setup_norm1_1norm05_n8_notsimulated),
c(index=30,l_setup_norm1_1norm05_n12_notsimulated),
c(index=39,l_setup_norm1_1norm05_n16_notsimulated),
c(index=48,l_setup_norm1_1norm05_n20_notsimulated),
c(index=10,l_setup_norm1_10norm05_n4_notsimulated),
c(index=11,l_setup_norm1_10norm05_n6_notsimulated),
c(index=12,l_setup_norm1_10norm05_n8_notsimulated),
c(index=31,l_setup_norm1_10norm05_n12_notsimulated),
c(index=40,l_setup_norm1_10norm05_n16_notsimulated),
c(index=49,l_setup_norm1_10norm05_n20_notsimulated),
c(index=13,l_setup_norm0_01norm05_n4_notsimulated),
c(index=14,l_setup_norm0_01norm05_n6_notsimulated),
c(index=15,l_setup_norm0_01norm05_n8_notsimulated),
c(index=32,l_setup_norm0_01norm05_n12_notsimulated),
c(index=41,l_setup_norm0_01norm05_n16_notsimulated),
c(index=50,l_setup_norm0_01norm05_n20_notsimulated),
c(index=16,l_setup_norm1_01norm05_n4_notsimulated),
c(index=17,l_setup_norm1_01norm05_n6_notsimulated),
c(index=18,l_setup_norm1_01norm05_n8_notsimulated),
c(index=33,l_setup_norm1_01norm05_n12_notsimulated),
c(index=42,l_setup_norm1_01norm05_n16_notsimulated),
c(index=51,l_setup_norm1_01norm05_n20_notsimulated),
c(index=19,l_setup_exp1_norm05_n4_notsimulated),
c(index=20,l_setup_exp1_norm05_n6_notsimulated),
c(index=21,l_setup_exp1_norm05_n8_notsimulated),
c(index=34,l_setup_exp1_norm05_n12_notsimulated),
c(index=43,l_setup_exp1_norm05_n16_notsimulated),
c(index=52,l_setup_exp1_norm05_n20_notsimulated),
c(index=22,l_setup_exp10_norm05_n4_notsimulated),
c(index=23,l_setup_exp10_norm05_n6_notsimulated),
c(index=24,l_setup_exp10_norm05_n8_notsimulated),
c(index=35,l_setup_exp10_norm05_n12_notsimulated),
c(index=44,l_setup_exp10_norm05_n16_notsimulated),
c(index=53,l_setup_exp10_norm05_n20_notsimulated),
c(index=25,l_setup_exp01_norm05_n4_notsimulated),
c(index=26,l_setup_exp01_norm05_n6_notsimulated),
c(index=27,l_setup_exp01_norm05_n8_notsimulated),
c(index=36,l_setup_exp01_norm05_n12_notsimulated),
c(index=45,l_setup_exp01_norm05_n16_notsimulated),
c(index=54,l_setup_exp01_norm05_n20_notsimulated)
)

l_setup_norm0_1norm05_n400_onlyPop_notsimulated<-list(n=400,pop_size=1000,delta=0.01,alpha=0.01,rG=f_CKQSO_kerneldist_norm_05,rG_pop=f_CKQSO_kernel_norm_05,vG=0.5,rF=f_CKQSO_seed_norm_0_1,vF=1,m=0,otherparams=list(outfile="norm0_1norm05_n400_onlyPop.txt"),b_dosimul=TRUE,b_doplot=TRUE,b_dosave=TRUE,c_fileprefix="norm0_1norm05_n400_onlyPop",res_exact=NULL,res_approxBT=NULL,res_approxBF=NULL,res_popAlg=NULL,legendpos="topleft",b_replicate=FALSE,b_save_seeds=TRUE,b_exact=FALSE,b_approxBT=FALSE,b_approxBF=FALSE,b_popAlg=TRUE)

l_all_study_PopAlgsetups<-list(
c(index=4,l_setup_norm0_1norm05_n400_onlyPop_notsimulated)
)
